import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box , Container} from "@chakra-ui/react"
import { Children } from 'react'

export default function Home({children, router}) {
  return (
    <Box as='main' pb={8}>
    <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>
    </Box>
  )
}
