import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import HomePage from './homePage'
import Services from './services';
import Work from './work';
import Clients from './clients'
import Contact from './contact'
import Footer from './footer'

export default function Home() {
  return (
    <div>
    <Head>
        <title>Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        <HomePage/>
        <Services/>
        <Work/>
        <Clients/>
        <Contact/>
        <Footer/>
      </div>    
  )
}
